name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v3
          with:
            node-version: 16.x
            cache: yarn
        - uses: webfactory/ssh-agent@v0.5.0
          with:
            ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
        - name: Deploy to GitHub Pages
          env:
            USE_SSH: true
          run: |
            git config --global user.email "actions@github.com"
            git config --global user.name "gh-actions"
            yarn install --frozen-lockfile
            yarn build
            echo 'staging2.docs.astar.network' > astar-docs/static/CNAME
            PUBLISHING=true PROJECT_NAME=astar-docs-staging yarn deploy

